#!/usr/bin/env bash
# Configures localhost and facebook.com to resolve to specific IP addresses

sed -i '/[[:space:]]localhost$/d' /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts

sed -i '/[[:space:]]facebook\.com$/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts